### ISSUE TITLE
why is there less visualiser?

### ISSUE THREAD

**Issue by shafiahaz2478** [elias123tre/lively-audio-visualizer#3]
this is not an issue or idont but i have less visualizer its not as much as you have on the page theres no customize option for it
![Uploading image.png…]()

**Comment by kkarakk** [comment]
equip the wallpaper, then right click the lively wallpaper icon  in taskbar. in the right click context menu click customization options. will show customization options then  
![image](https://user-images.githubusercontent.com/911913/135150518-6a8b6b78-f48f-43a6-8ace-dbb50f38d8db.png)
