### ISSUE TITLE
I messed up somewhere

### ISSUE THREAD

**Issue by Nitrowing** [elias123tre/lively-audio-visualizer#8]
![Lively](https://github.com/user-attachments/assets/b9e4ad0c-9c1c-45b9-a96e-cff16fde6998)

Media wallpapers show this text.

**Comment by eliasfloreteng** [comment]
I think you are using the built in music visualizer (with my version imported somehow?) instead of my custom wallpaper. See the install instructions in the [README](https://github.com/elias123tre/lively-audio-visualizer#lively-audio-visualizer)

**Comment by Nitrowing** [comment]
I think I botched the install before getting it right. Do you know where this text is generated?

**Comment by eliasfloreteng** [comment]
It could be that you have a tab in the background playing the video from the github page? Or that you maybe imported the theme as a sound file somewhere
